export const backgrounds = [
  'Fiery',
  'Citrus',
  'Fuchsia',
  'Blush',
  'Sky',
  'Midnight',
  'Forest',
  'Zest',
  'Slate',
  'Noir',
  'Sunny',
  'Regal',
];

export const programmingLanguages = [
  { readableLanguage: 'XML', hljsLanguage: 'xml', disabled: true },
  { readableLanguage: 'Bash', hljsLanguage: 'bash', disabled: true },
  { readableLanguage: 'C', hljsLanguage: 'c', disabled: true },
  { readableLanguage: 'C++', hljsLanguage: 'cpp', disabled: true },
  { readableLanguage: 'C#', hljsLanguage: 'csharp', disabled: true },
  { readableLanguage: 'Markdown', hljsLanguage: 'markdown', disabled: false },
  { readableLanguage: 'Diff', hljsLanguage: 'diff', disabled: true },
  { readableLanguage: 'Ruby', hljsLanguage: 'ruby', disabled: true },
  { readableLanguage: 'Go', hljsLanguage: 'go', disabled: true },
  { readableLanguage: 'GraphQL', hljsLanguage: 'graphql', disabled: false },
  { readableLanguage: 'INI', hljsLanguage: 'ini', disabled: true },
  { readableLanguage: 'Java', hljsLanguage: 'java', disabled: true },
  {
    readableLanguage: 'JavaScript',
    hljsLanguage: 'javascript',
    disabled: false,
  },
  { readableLanguage: 'JSON', hljsLanguage: 'json', disabled: true },
  { readableLanguage: 'Kotlin', hljsLanguage: 'kotlin', disabled: true },
  { readableLanguage: 'Less', hljsLanguage: 'less', disabled: true },
  { readableLanguage: 'Lua', hljsLanguage: 'lua', disabled: true },
  { readableLanguage: 'Makefile', hljsLanguage: 'makefile', disabled: true },
  { readableLanguage: 'Perl', hljsLanguage: 'perl', disabled: true },
  {
    readableLanguage: 'Objective-C',
    hljsLanguage: 'objectivec',
    disabled: true,
  },
  { readableLanguage: 'PHP', hljsLanguage: 'php', disabled: false },
  {
    readableLanguage: 'PHP Template',
    hljsLanguage: 'php-template',
    disabled: true,
  },
  {
    readableLanguage: 'Plain Text',
    hljsLanguage: 'plaintext',
    disabled: true,
  },
  { readableLanguage: 'Python', hljsLanguage: 'python', disabled: true },
  {
    readableLanguage: 'Python REPL',
    hljsLanguage: 'python-repl',
    disabled: true,
  },
  { readableLanguage: 'R', hljsLanguage: 'r', disabled: true },
  { readableLanguage: 'Rust', hljsLanguage: 'rust', disabled: true },
  { readableLanguage: 'SCSS', hljsLanguage: 'scss', disabled: false },
  { readableLanguage: 'Shell', hljsLanguage: 'shell', disabled: true },
  { readableLanguage: 'SQL', hljsLanguage: 'sql', disabled: true },
  { readableLanguage: 'Swift', hljsLanguage: 'swift', disabled: true },
  { readableLanguage: 'YAML', hljsLanguage: 'yaml', disabled: true },
  {
    readableLanguage: 'TypeScript',
    hljsLanguage: 'typescript',
    disabled: false,
  },
  { readableLanguage: 'VB.NET', hljsLanguage: 'vbnet', disabled: true },
  { readableLanguage: 'WebAssembly', hljsLanguage: 'wasm', disabled: true },
];

export const highlightStyles = [
  'atom-one-dark',
  'an-old-hope',
  'arta',
  'ashes',
  'atelier-cave',
  'atelier-dune',
  'atelier-estuary',
  'atelier-forest',
  'atelier-lakeside',
  'atelier-plateau',
  'atelier-savanna',
  'atelier-seaside',
  'atlas',
  'bespin',
  'chalk',
  'circus',
  'classic-dark',
  'codeschool',
  'colors',
  'darcula',
  'dark-violet',
  'darkmoss',
  'darktooth',
  'decaf',
  'default-dark',
  'dracula',
  'edge-dark',
];
